apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
  labels:
    env: prod
spec:
  containers:
    - name: nginx-1
      image: nginx
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"

  