apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: front-end
spec:
  replicas: 3
  template:
    metadata:
      name: myapp-nginx
      labels:
        name: myapp
        type: front-end
    spec:
      containers:
      - name: ng-myapp
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

    