apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc1
spec:
  replicas: 3
  selector:
    app: myapp
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-nginx
          image: nginx
