apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myreplicaset
  labels:
    app: myapp
    key: value
spec:
  replicas: 3
  selector:
    matchLabels:
      name: pod-myapp
  template:
    metadata:
      name: myapp-pod
      labels:
        name: pod-myapp
    spec:
      containers:
        - name: myapp
          image: nginx
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
